blog_posts/urls.py
from django.contrib import admin
from django.urls import path
from blog_posts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.post_list,name = 'post_list'),
    path('new',views.post_create, name= 'post_new'),
    path('edit',views.post_update, name = 'post_edit'),
    path('delete', views.post_delete, name = 'post_delete'),
]

crudapp/urls.py
from django.contrib import admin
from django.urls import path, include
from crudapp.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog_posts/', include('blog_posts.urls', namespace= 'blog_posts')),
    path('',home, name = 'home'),
]

blog_posts/models.py
from django.db import models
from __future__ import unicorn_literals


class blog_posts(models.Model):
    title = models.CharField(max_length= 100)
    tag = models.CharField(max_length=40)
    author = models.CharField(max_length= 30)

    def __unicode__(self):
        return self.title

    def get_post_url(self):
        return reverse('post_edit',kwargs ={'pk' : self.pk})

blog_posts/views.py
from django.shortcuts import render
from __future__ import unicode_literals
from django.forms import ModelForm
from blog_posts.models import blog_posts

class PostsForm(ModelForm):
    class Meta:
        model = blog_posts
        fields = ['id','title','author']

def post_list(request, template_name = 'blog_posts/post_lists.html'):
    posts = blog_posts.objects.all()
    data = {}
    data['object_list'] = posts
    return render(request,template_name,data)

def post_create(request, template_name = 'blog_posts/post_form.html'):
    form = PostsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'form': form})

def post_update(request, pk , template_name = 'blog_posts/post_form.html'):
    post = get_object_or_404(blog_posts , pk = pk)
    form = PostsForm(request.POST or None, instance= post)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name,{'form': form})

def post_delete(request , pk ,template_name = 'blog_posts/post_delete.html'):
    post = get_object_or_404(blog_posts ,pk = pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog_posts:post_list')
    return render(request,template_name, {'object':post})

blog_posts/templates/blog_posts/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application</title>
</head>
<body>
    <div class = "container">
        <form method = "post">
            {% csrf_token %}
            {{form.as_p}}
            <input class = "btn btn-primary" type = "submit" value = "Submit" />
        </form>
    </div>
    
</body>
</html>

blog_posts/templates/blog_posts/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application</title>
</head>
<body>
    <div class="Container">
        <h1>Blog Post List!</h1>
        <ul>
            {% for post in object_list %}
            <li><p>Post ID: <a href = {%url "blog_posts:post_edit" post.id %}">{{post.id}}</a></p>
            <p> Title : {{post. title}}</p>
            <a href = "{% url "blog_posts:post_delete" post.id %}">Delete</a>
        </li>
        {% endfor %}
        </ul>

        <a href="{%url"blog_posts:post_new" %}">New Blog post entry</a>
    </div>
    
</body>

</html>

blog_posts/templates/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <title>Django CRUD application</title>
</head>
<body>
    <div class = "container">
        <form method="post"> {%csrf_token%}
            Are you sure you wanna delete "{{object}}" ?
            <input class="btn btn-primary" type = "submit" value= "Submit"/>
        </form>
    </div>
</body>
</html>